#!/bin/sh

file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit 1

lilyrun() { \
	command="lilypond"
	( head -n5 "$file" | grep -qi 'project' ) && command="lilypond-build"
	$command "$file"
}

case "$ext" in
	[0-9]) preconv "$file" | refer -PS -e | groff -mandoc -T pdf > "$base".pdf ;;
	c) cc "$file" -o "$base" && "$base" ;;
	cpp) g++ "$file" -o "$base" && "$base" ;;
	cs) mcs "$file" && mono "$base".exe ;;
	go) go run "$file" ;;
	h) sudo make install ;;
	java) javac -d classes "$file" && java -cp classes "${1%.*}" ;;
	ly) lilyrun "$file" ;;
	m) octave "$file" ;;
	md) lowdown -tterm "$file" >> /tmp/lowdown.script.txt ; st -e less -R /tmp/lowdown.script.txt ; rm -rf /tmp/lowdown.script.txt ;;
	mom) preconv "$file" | refer -PS -e | groff -mom -kept -T pdf > "$base".pdf ;;
	ms) preconv "$file" | refer -PS -e -p "$HOME/.local/share/groff/library.txt" | groff -U -ms -kept -dpaper=letter -T pdf > "$base".pdf ;;
	py) python "$file" ;;
	rs) cargo build ;;
	sass) sassc -a "$file" "$base.css" ;;
	scad) openscad -o "$base".stl "$file" ;;
	sent) setsid -f sent "$file" 2>/dev/null ;;
	*) sed -n '/^#!/s/^#!//p; q' "$file" | xargs -r -I % "$file" ;;
esac
