#!/bin/sh

file=$(readlink -f "$1")
directory="${file%/*}"
base="${file%.*}"
extension="${file##*.}"
baseName="${base##*/}"
directoryName="${directory##*/}"

cd "$directory" || exit 1

lilypondPreview() { \
	case "$directoryName" in
		variables) cd .. ;;
		eng-files) cd .. ;;
		front-matter) cd .. ;;
		manuscripts) cd .. ;;
	esac
	directoryName="${PWD##*/}"
	cat variables/*.ly eng-files/*.ly front-matter/*.ly *.ly |
		lilypond -dno-point-and-click --output=/tmp/"$directoryName"-compiler - &&
			zathura /tmp/"$directoryName"-compiler.pdf &&
				rm -rf /tmp/"$directoryName"-compiler.pdf
}

check() { \
	command=$2
	( head -n1 "$file" | grep -qi 'project' ) && command="lilypondPreview"
	( head -n1 "$file" | grep -qi 'module' ) && command="infoGroffMs"
	$command $1
}

groffMs() { \
	preconv $1 | refer -PS -e -p "$HOME/.local/share/groff/library.txt" | groff -U -ms -kept -dpaper=letter -T pdf > "$base".pdf
}

case "$extension" in
	[0-9]) preconv "$file" | refer -PS -e | groff -mandoc -T pdf > "$base".pdf ;;
	c) cc "$file" -o "$base" && "$base" ;;
	cpp) g++ "$file" -o "$base" && "$base" ;;
	cs) mcs "$file" && mono "$base".exe ;;
	go) go run "$file" ;;
	h) sudo make install ;;
	java) javac -d classes "$file" && java -cp classes "${1%.*}" ;;
	ly) check "$file" lilypond ;;
	m) octave "$file" ;;
	md) lowdown -tterm "$file" >> /tmp/"$baseName"-compiler.txt &&
		st -e less -R /tmp/"$baseName"-compiler.txt ; rm -rf /tmp/"$baseName"-compiler.txt ;;
	mom) preconv "$file" | refer -PS -e | groff -mom -kept -T pdf > "$base".pdf ;;
	ms) check "$file" groffMs ;;
	py) python "$file" ;;
	rs) cargo build ;;
	sass) sassc -a "$file" "$base.css" ;;
	scad) openscad -o "$base".stl "$file" ;;
	sent) setsid -f sent "$file" 2>/dev/null ;;
	*) sed -n '/^#!/s/^#!//p; q' "$file" | xargs -r -I % "$file" ;;
esac
