#!/bin/sh

# returns an aproximation of samples in a given wav file using ffprobe.

trim=$(ffprobe -i "$1" 2>&1 | awk '/Input/ {p=1;next}p' | sed 's/  Duration: //g; s/, bitrate:.*//g; s/.*), //g; s/ Hz.*//g;')
dur=$(echo "$trim" | sed '2d;' | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
sam=$(echo "$trim" | sed '1d;')
frames=$(echo $sam \* $dur | bc | sed 's/\.00//g; s/\.0//g;')
frames=$(($frames-500))

echo "$frames"
