#!/bin/sh

file=$(readlink -f "$1")
name=$(basename "$file" | sed 's/.ly//')

case "${PWD##*/}" in
	manuscripts) cat ../variables/*.ly ../eng-files/paper.ly "$file" |
		lilypond -dno-point-and-click --output="$name"-compiler - &&
			zathura /tmp/"$directoryName"-compiler.pdf &&
				rm -rf /tmp/"$directoryName"-compiler.pdf ;;
	*) echo "not a manuscript file" ;
esac
