#!/bin/sh

file=$(readlink -f "$1")
dir=${PWD##*/}
proj="$(basename "$(dirname "${PWD}")")"
base="${file%.*}"
ext="${file##*.}"

case "$dir" in
	manuscripts) cat ../variables/*.ly ../eng-files/paper.ly "$file" > "$base".ly-tmp && lilypond "$base".ly-tmp ; rm -f "$base".ly-tmp ;;
	*) echo "not a manuscript file" ;
esac
