#!/bin/sh

file=$(readlink -f "$1")

case "${PWD##*/}" in
	manuscripts) cat ../variables/*.ly ../eng-files/paper.ly "$file" |
		lilypond --output="$(basename "$(dirname "${PWD}")")-$(basename "$file" | sed 's/.ly//' )" -  ;;
	*) echo "not a manuscript file" ;
esac
