#!/bin/sh

case "${PWD##*/}" in
	variables) cat ../variables/*.ly ../eng-files/*.ly ../front-matter/*.ly ../*.ly |
		lilypond -dno-point-and-click --output=../"$(basename "$(dirname "${PWD}")")" - ;;
	eng-files) cat ../variables/*.ly ../eng-files/*.ly ../front-matter/*.ly ../*.ly |
		lilypond -dno-point-and-click --output=../"$(basename "$(dirname "${PWD}")")" - ;;
	front-matter) cat ../variables/*.ly ../eng-files/*.ly ../front-matter/*.ly ../*.ly |
		lilypond -dno-point-and-click --output=../"$(basename "$(dirname "${PWD}")")" - ;;
	manuscripts) cat ../variables/*.ly ../eng-files/*.ly ../front-matter/*.ly ../*.ly |
		lilypond -dno-point-and-click --output=../"$(basename "$(dirname "${PWD}")")" -  ;;
	*) cat variables/*.ly eng-files/*.ly front-matter/*.ly *.ly |
		lilypond -dno-point-and-click --output="${PWD##*/}" - ;
esac
