#!/bin/sh

run_to_play () {
	sed -i 's/\%\\midi/\\midi/' ../manuscripts/*.ly ; sed -i 's/\%\\midi/\\midi/' ../*.ly
	cat ../variables/*.ly ../eng-files/*.ly ../front-matter/*.ly ../book.ly |
	lilypond -s --output=../"$(basename "$(dirname "${PWD}")")" - || exit
	dec=$(find .. -name "*.midi" | sed 's/..\///; s/.midi//' | nl -w2 -s'> ' - )
	echo "$dec"
	read -r -p "Which file to play? (1, 2, 3, etc)  " choice
	play=$( echo "$dec" | sed ""$choice"!d" | sed "s/ "$choice"> //; s/$/.midi/;")
	echo "Loading $play in fluidsynth"
	fluidsynth -q -a pulseaudio /etc/soundfonts/SALC5-Light-SF-v2_7/SalC5Light2.sf2 ../"$play" 2> /dev/null
	sed -i 's/\\midi/\%\\midi/' ../manuscripts/*.ly ; sed -i 's/\\midi/\%\\midi/' ../*.ly ; rm -f ../*.midi
}

do_to_play () {
	sed -i 's/\%\\midi/\\midi/' manuscripts/*.ly ; sed -i 's/\%\\midi/\\midi/' *.ly
	cat variables/*.ly eng-files/*.ly front-matter/*.ly *.ly |
	lilypond -s --output="${PWD##*/}" - || exit
	dec=$(find . -name "*.midi" | sed 's/.\///; s/.midi//' | nl -w2 -s'> ' - )
	echo "$dec"
	read -r -p "Which file to play? (1, 2, 3, etc)  " choice
	play=$( echo "$dec" | sed ""$choice"!d" | sed "s/ "$choice"> //; s/$/.midi/;")
	echo "Loading $play in fluidsynth"
	fluidsynth -q -a pulseaudio /etc/soundfonts/SALC5-Light-SF-v2_7/SalC5Light2.sf2 "$play" 2> /dev/null
	sed -i 's/\\midi/\%\\midi/' manuscripts/*.ly ; sed -i 's/\\midi/\%\\midi/' ./*.ly ; rm -f *.midi
}

case "${PWD##*/}" in
	front-matter) run_to_play;;
	eng-files) run_to_play ;;
	variables) run_to_play ;;
	manuscripts) run_to_play ;;
	*) do_to_play ;
esac
